directories:
  mirror_module_path: False
  base: "D:/GitHub/manim_project/manimgl"
  subdirs:
    output: "D:/GitHub/manim_project/videos"
    raster_images: "../images/raster_image"
    vector_images: "../images/vector_images"
    # Use the default value for the rest
window:
  position_string: UR
  monitor_index: 1
  full_screen: False
camera:
  resolution: (1920, 1080)
  background_color: "#000000"
  fps: 30
  background_opacity: 1.0
file_writer:
  saturation: 1.5
text:
  font: "CMU Serif"
  alignment: "CENTER"
tex:
  template: "default"
embed:
  autoreload: True
ignore_manimlib_modules_on_reload: True
